if(EXISTS "/home/lyricx/cmu_15445/bustub-private/build_local/test/b_plus_tree_delete_test[1]_tests.cmake")
  include("/home/lyricx/cmu_15445/bustub-private/build_local/test/b_plus_tree_delete_test[1]_tests.cmake")
else()
  add_test(b_plus_tree_delete_test_NOT_BUILT b_plus_tree_delete_test_NOT_BUILT)
endif()
