if(EXISTS "/home/lyricx/cmu_15445/bustub-private/build_local/test/binder_test[1]_tests.cmake")
  include("/home/lyricx/cmu_15445/bustub-private/build_local/test/binder_test[1]_tests.cmake")
else()
  add_test(binder_test_NOT_BUILT binder_test_NOT_BUILT)
endif()
