if(EXISTS "/home/lyricx/cmu_15445/bustub-private/build_local/test/buffer_pool_manager_test[1]_tests.cmake")
  include("/home/lyricx/cmu_15445/bustub-private/build_local/test/buffer_pool_manager_test[1]_tests.cmake")
else()
  add_test(buffer_pool_manager_test_NOT_BUILT buffer_pool_manager_test_NOT_BUILT)
endif()
