if(EXISTS "/home/lyricx/cmu_15445/bustub-private/build_local/test/clock_replacer_test[1]_tests.cmake")
  include("/home/lyricx/cmu_15445/bustub-private/build_local/test/clock_replacer_test[1]_tests.cmake")
else()
  add_test(clock_replacer_test_NOT_BUILT clock_replacer_test_NOT_BUILT)
endif()
