if(EXISTS "/home/lyricx/cmu_15445/bustub-private/build_local/test/crash_test[1]_tests.cmake")
  include("/home/lyricx/cmu_15445/bustub-private/build_local/test/crash_test[1]_tests.cmake")
else()
  add_test(crash_test_NOT_BUILT crash_test_NOT_BUILT)
endif()
