if(EXISTS "/home/lyricx/cmu_15445/bustub-private/build_local/test/disk_scheduler_test[1]_tests.cmake")
  include("/home/lyricx/cmu_15445/bustub-private/build_local/test/disk_scheduler_test[1]_tests.cmake")
else()
  add_test(disk_scheduler_test_NOT_BUILT disk_scheduler_test_NOT_BUILT)
endif()
