if(EXISTS "/home/lyricx/cmu_15445/bustub-private/build_local/test/disk_manager_test[1]_tests.cmake")
  include("/home/lyricx/cmu_15445/bustub-private/build_local/test/disk_manager_test[1]_tests.cmake")
else()
  add_test(disk_manager_test_NOT_BUILT disk_manager_test_NOT_BUILT)
endif()
