if(EXISTS "/home/lyricx/cmu_15445/bustub-private/build_local/test/hyperloglog_test[1]_tests.cmake")
  include("/home/lyricx/cmu_15445/bustub-private/build_local/test/hyperloglog_test[1]_tests.cmake")
else()
  add_test(hyperloglog_test_NOT_BUILT hyperloglog_test_NOT_BUILT)
endif()
