if(EXISTS "/home/lyricx/cmu_15445/bustub-private/build_local/test/lru_replacer_test[1]_tests.cmake")
  include("/home/lyricx/cmu_15445/bustub-private/build_local/test/lru_replacer_test[1]_tests.cmake")
else()
  add_test(lru_replacer_test_NOT_BUILT lru_replacer_test_NOT_BUILT)
endif()
