if(EXISTS "/home/lyricx/cmu_15445/bustub-private/build_local/test/orset_test[1]_tests.cmake")
  include("/home/lyricx/cmu_15445/bustub-private/build_local/test/orset_test[1]_tests.cmake")
else()
  add_test(orset_test_NOT_BUILT orset_test_NOT_BUILT)
endif()
