if(EXISTS "/home/lyricx/cmu_15445/bustub-private/build_local/test/skiplist_test[1]_tests.cmake")
  include("/home/lyricx/cmu_15445/bustub-private/build_local/test/skiplist_test[1]_tests.cmake")
else()
  add_test(skiplist_test_NOT_BUILT skiplist_test_NOT_BUILT)
endif()
