if(EXISTS "/home/lyricx/cmu_15445/bustub-private/build_local/test/tmp_tuple_page_test[1]_tests.cmake")
  include("/home/lyricx/cmu_15445/bustub-private/build_local/test/tmp_tuple_page_test[1]_tests.cmake")
else()
  add_test(tmp_tuple_page_test_NOT_BUILT tmp_tuple_page_test_NOT_BUILT)
endif()
