if(EXISTS "/home/lyricx/cmu_15445/bustub-private/build_local/test/trie_test[1]_tests.cmake")
  include("/home/lyricx/cmu_15445/bustub-private/build_local/test/trie_test[1]_tests.cmake")
else()
  add_test(trie_test_NOT_BUILT trie_test_NOT_BUILT)
endif()
