if(EXISTS "/home/lyricx/cmu_15445/bustub-private/build_local/test/txn_timestamp_test[1]_tests.cmake")
  include("/home/lyricx/cmu_15445/bustub-private/build_local/test/txn_timestamp_test[1]_tests.cmake")
else()
  add_test(txn_timestamp_test_NOT_BUILT txn_timestamp_test_NOT_BUILT)
endif()
