if(EXISTS "/home/lyricx/cmu_15445/bustub-private/build_local/test/type_test[1]_tests.cmake")
  include("/home/lyricx/cmu_15445/bustub-private/build_local/test/type_test[1]_tests.cmake")
else()
  add_test(type_test_NOT_BUILT type_test_NOT_BUILT)
endif()
